server:
  port: 8763

spring:
  profiles:
    active: dev
  application:
    name: pp-open-pay2
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# mybatis
mybatis-plus:
  mapper-locations: com/project/dao/*/*.xml

logging:
  level:
    com.alibaba.nacos.client.naming: error
    com.project.dao: DEBUG