server:
  port: 8763

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev
  application:
    name: pp-open-pay2
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true

# mybatis
mybatis-plus:
  mapper-locations: com/project/dao/*/*.xml

logging:
  level:
    com.project.dao: DEBUG