server:
  port: 8762

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  profiles:
    active: dev
  application:
    name: pp-web
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true

logging:
  level:
    com.project.dao: DEBUG