spring:
  datasource:
    url: jdbc:mysql://47.95.14.140:3306/project?characterEncoding=utf8&useSSL=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: server
    password: server
  redis:
    host: 47.95.14.140
    password: 123456
    database: 0
    jedis:
      pool:
        max-idle: 1
        max-active: 8
        min-idle: 1
        max-wait: -1
  rabbitmq:
    host: 47.95.14.140
    username: server
    password: server
    port: 5672