server:
  port: 8762

spring:
  profiles:
    active: dev
  application:
    name: pp-system-admin
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: yupan03sdife

logging:
  level:
    com.project.dao: DEBUG