server:
  port: 8762

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev
  application:
    name: pp-system-admin
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml


jwt:
  secret: yupan03sdife

logging:
  level:
    com.project.dao: DEBUG