server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://47.93.219.196:3306/project?characterEncoding=utf8&useSSL=false&verifyServerCertificate=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: server
    password: server
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: KevinHikariPool
      maximum-pool-size: 12
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 50000
      max-lifetime: 540000