server:
  port: 8762
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  application:
    name: pp-system-admin
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/**.xml

jwt:
  secret: yupan03sdife

logging:
  level:
    com.project.dao: DEBUG