spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/project?characterEncoding=utf8&useSSL=false&verifyServerCertificate=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: KevinHikariPool
      maximum-pool-size: 12
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 50000
      max-lifetime: 540000
  redis:
    host: 127.0.0.1
    # password: yupan03
    jedis:
      pool:
        max-idle: 1
        max-active: 8
        min-idle: 1
        max-wait: -1
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    # 消息发送到交换机确认
    publisher-confirms: true
    # 消息发送到队列确认
    publisher-returns: true
    port: 5672
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual

file_path: C:\file_service\pp