server:
  port: 8769

spring:
  profiles:
    active: dev
  application:
    name: pp-open-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    gateway:
#      discovery:
#        locator:
#          enabled: true  #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
#          lowerCaseServiceId: true   #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上。
#          filters:
#            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: '*'
# Feign/Ribbon第一次请求失败
ribbon:
  eager-load:
    enabled: true

# 配置输出日志
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    
# mybatis
mybatis-plus:
  mapper-locations: com/project/dao/*/*.xml