server:
  port: 8888

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG

swagger:
  enable: true

wx:
  mp:
    # 微信公众号
    appId: wx003b688800493d01 
    secret: 0718cc31b1fc9235d3b38990c7995923
    token: yupan03
    aesKey: 111
  pay:
    # 微信商户号
    appId: wx6ba82710094d521c
    mchId: 1503729301
    mchKey: E2c761o4ELXbswyYQ8aPdhcNBATljBFh
    # subAppId:
    # subMchId:
    keyPath: /usr/local/file_service/cixi_file/apiclient_cert/apiclient_cert.p12
  miniapp:
    # 微信小程序
    appId: wx41563a72bbf9022d
    appSecret: fe8ceb054f5a9740b9ebe60fc65fbe1e
    token: #微信小程序消息服务器配置的token
    aesKey: #微信小程序消息服务器配置的EncodingAESKey
    msgDataFormat: JSON